services:
  db-hackthelove:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-hackthelove:/var/lib/postgresql/data
    networks:
      - app_network

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     PRODUCTION: 1
  #     APP_PORT: ${APP_PORT}
  #     DB_CONNECTION: pgsql
  #     DB_HOST: db-hackthelove
  #     DB_PORT: ${DB_PORT}
  #     DB_DATABASE: ${DB_DATABASE}
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     SECRET_KEY: ${SECRET_KEY}
  #     GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  #     TIME_RELEASE_MATCH: ${TIME_RELEASE_MATCH}
  #     LOG_LEVEL: ${LOG_LEVEL}
  #     GIN_MODE: release
  #     MIN_VALUE_COMPATIBILITY: ${MIN_VALUE_COMPATIBILITY}
  #     BATCH_SIZE: ${BATCH_SIZE}
  #     MAX_PHOTO_NUMBER: ${MAX_PHOTO_NUMBER}
  #     REQUEST_PER_SECOND: ${REQUEST_PER_SECOND}
  #     ALLOWED_ORIGINS: "https://hackthe.love,http://localhost:5173"
  #   depends_on:
  #     - db-hackthelove
  #   ports:
  #     - "${APP_PORT}:8080"
  #   networks:
  #     - app_network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     - VITE_API_URL=${BACKEND_URL}
  #     - BACKEND_URL=${BACKEND_URL}
  #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
  #     - TIME_RELEASE_MATCH=${TIME_RELEASE_MATCH}
  #   ports:
  #     - "${APP_PORT_FE}:80"
  #   networks:
  #     - app_network

networks:
  app_network:

volumes:
  db-hackthelove:
  umami-db-data:
